# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "db01"
    config.vm.hostname = "db01"
    config.vm.box = "ubuntu/focal64"
    config.vm.network "private_network", ip: "192.168.56.4"
    config.vm.network "forwarded_port",guest: 3306,host: 3310
    config.vm.provision "shell", path: "provision.sh"
  end
  