# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "control-node"
  config.vm.hostname = "control-node"
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ["vers=4,tcp"]
  config.vm.provision "shell", path: "provision.sh"
end
