---
- name: Instalação do MySQL e criação de banco de dados e usuário
  hosts: dbs
  become: yes

  vars:
    mysql_root_password: "ragnarok0"
    mysql_db_name: "devops"
    mysql_user_name: "root"
    mysql_user_password: "ragnarok0"
    mysql_user: root
    mysql_password: ragnarok0
  tasks:
  - name: Instala o pacote do MySQL
    apt:
      name: mysql-server
      state: present
  - name: Instala o python3-pip 
    apt:
      name: python3-pip
      state: present 
  - name: Instala o pymysql
    pip:
      name: pymysql
      state: present
      executable: pip3 

  - name: Inicia o serviço MySQL
    service:
      name: mysql
      state: started

  - name: Cria banco de dados
    mysql_db:
      name: "{{ mysql_db_name }}"
      state: present

  - name: Cria usuário e concede acesso total ao banco de dados
    mysql_user:
      name: "{{ mysql_user_name }}"
      password: "{{ mysql_user_password }}"
      priv: "{{ mysql_db_name }}.*:ALL"
      host: localhost
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

